### PR TITLE
Added pausing and resuming facilities for Windows and Linux environme…

### PR DESCRIPTION
**Pull request by chandeepadissanayake**
I've added the methods which would facilitate the user with the ability to pause and resume a playback.

### CODE REVIEW

**Comment by hamiltron** [comment]
@chandeepadissanayake I apologize for not responding sooner. It's been very hard to dedicate any time to this recently. I looked over your PR and it's very nice work in C, especially conforming to the style of the existing code - very well done. However, probably the most important goal of this library is to be robustly cross-platform... meaning that if it works on Windows, it needs to work on Linux and macOS. Given that, I can't introduce a feature that only works for two platforms. If you can work in the equivalent functionality for macOS, I'll work with you toward getting this merged in.

**Comment by chandeepadissanayake** [comment]
@hamiltron Thanks for your compliments. I understand your premise. I believe I can work on making pause and resume facilities cross-platform. I will re-post while I have that completed. I would need several days as I'm bit busy currently.

**Comment by hamiltron** [comment]
Closing this due to updates for macOS never having been submitted.

**Comment by jmcmahon443** [comment]
@chandeepadissanayake forgive me for reviving this. Do your changes allow audio to be played at an arbitrary time (t=5s for example) instead of always starting at time=0s? If it does, it's worth noting that feature is powerful.

**Comment by chandeepadissanayake** [comment]
@jmcmahon443 Sorry for taking too long to reply.  Yes it allows resuming audio from the moment it was paused on. It would be worth noting that these changes are not to start the playback at some point in time t != 0s but only to pause and resume onwards from the point it was paused on.

**Pull request closed without merging**
