### PR TITLE
Fix punctuation error

### PR DESCRIPTION
**Pull request by kerbingamer376**
you had an apostrophe in the wrong place.

### CODE REVIEW

**Comment by hamiltron** [comment]
Thanks for the suggestion. Usage of apostrophes in English, like many things, is inconsistent in general. I dug up [this in a quick search](http://www.dailywritingtips.com/when-to-form-a-plural-with-an-apostrophe/) and I think it underscores that point. If we all decided to remove them from usage entirely, I'd happily jump on board. 😉  

More to the point, I have my own personal and informal rule that, when I'm documenting, I use apostrophes to pluralize class names  - mostly to aid in visual clarity. I'm open to debate, but for now I'm going to stick with that.

**Comment by kerbingamer376** [comment]
counters to this: [here](https://preciseedit.wordpress.com/2009/04/03/end-apostrophe-abuse/), [here](http://www.apostrophe.org.uk/page2.html) and [here](http://www.eng-lang.co.uk/apostrophe_rules.htm).  All three clearly state the apostrophe is NEVER to be used in plurals. 

Also, having personal rules on grammar? Isn't english a universal thing?

**Comment by hamiltron** [comment]
Thanks for the links. The first two links do backup your assertion; however, I would point out that the first one appears to be a personal blog post, and the second, the website of an apostrophe usage advocacy group (the internet is a strange place indeed), neither of which reference any authority on usage. (See the reference to the [CMS](https://en.wikipedia.org/wiki/The_Chicago_Manual_of_Style) in my link above.) 

For the third link, section three indicates usage of apostrophes to "indicate the structure of unusual words" and I think this gets at why I do this. There are vetted examples of this general concept and, unless someone can point out otherwise, there are no formal rules for pluralizing programming class names in English. I do it because **WaveObjects** *could* be a valid class name (and therefore might be confusing to an unfamiliar reader), whereas **WaveObject's** would not be a valid class name in most programming languages so there's less ambiguity. Admittedly, it's probably a small difference, but one I find *useful*. 

As for the universality of English, I won't try to argue either way, but I will betray my bias by recommending Pinker's [The Language Instinct](https://en.wikipedia.org/wiki/The_Language_Instinct) - one of the few books I've read but a good (and fun) one. Let's just say I find it squishy.

**Comment by kerbingamer376** [comment]
Your link was a blog post as well.

**Pull request closed without merging**
